version: "3.5"

services:
  openssl-helper:
    build: ./build
    image: openssl-helper
    container_name: openssl-helper
    hostname: openssl-helper
    volumes:
      - ../unix/certificates:/root/certificates
    entrypoint: /root/certificates/generateAll.sh